Repository opensourcestories/opensourcestories.org, pull requests merged in 2022-05, with the labels that each got.

#52 Test update baseurl to see if that helps podcast verification
  config.toml
Labels: bug

#50 Horizontally align and alphabetize the tags - Fix issue #48
  layouts/partials/tags.html
Labels: UX

#53 Add "Emma Irwin and open source maintainership"
  content/stories/2022/emma-irwin.md
Labels: story

#54 add links to podcasts on main page
  data/podcasts.json
  layouts/index.html
  layouts/partials/podcasts.html
  layouts/partials/svg/podcast.svg
  layouts/partials/svg/rss-raw.svg
  layouts/partials/svg/spotify.svg
  layouts/stories/stories.rss.xml
Labels: enhancement

#56 modify the schema markup for the site
  config.toml
  data/contributors.json
  layouts/_default/baseof.html
Labels: update

#57 fix relative url issue in RSS link
  layouts/_default/baseof.html
Labels: bug

#55 Add Dawn Wage's story and make it live
  content/stories/2022/dawn-wages.md
Labels: story

#58 migration to Blubrry
  content/stories/2021/aaron-patterson.md
  content/stories/2021/elana-hashman.md
  content/stories/2021/joe-beda.md
  content/stories/2021/josh-simmons.md
  content/stories/2021/russell-keith-magee.md
  content/stories/2021/samson-goddy.md
  content/stories/2022/dawn-wages.md
  content/stories/2022/emma-irwin.md
  content/stories/2022/nicolas-steenhout.md
Labels: bug

#59 remove itunes:title
  layouts/stories/stories.rss.xml
  netlify.toml
Labels: bug

#62 Add Google Podcasts and update README
  README.md
  data/podcasts.json
  layouts/partials/podcasts.html
  layouts/partials/svg/google.svg
Labels: enhancement
